# Generated by Django 5.1.7 on 2025-05-05 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_slug', models.CharField(max_length=255, verbose_name='اسلاگ شی')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='contenttypes.contenttype', verbose_name='نوع محتوا')),
            ],
            options={
                'verbose_name': 'بازدید محتوا',
                'verbose_name_plural': 'بازدیدهای محتوا',
                'indexes': [models.Index(fields=['content_type', 'object_slug', 'session_key'], name='VisitCounte_content_745fd4_idx')],
                'unique_together': {('content_type', 'object_slug', 'session_key')},
            },
        ),
    ]
