# Generated by Django 5.1.7 on 2025-04-28 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('VisitCounter', '0002_delete_view'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_slug', models.CharField(max_length=255, verbose_name='اسلاگ شی')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('ip_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='contenttypes.contenttype', verbose_name='نوع محتوا')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'بازدید محتوا',
                'verbose_name_plural': 'بازدیدهای محتوا',
                'indexes': [models.Index(fields=['content_type', 'object_slug', 'user', 'session_key', 'ip_hash'], name='VisitCounte_content_4d30ec_idx')],
                'unique_together': {('content_type', 'object_slug', 'user', 'session_key', 'ip_hash')},
            },
        ),
    ]
