# Generated by Django 5.1.7 on 2025-04-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VisitCounter', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentvisit',
            name='ip_hash',
            field=models.CharField(blank=True, editable=False, max_length=128, null=True),
        ),
    ]
