# Generated by Django 5.1.7 on 2025-04-29 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VisitCounter', '0004_alter_contentvisit_ip_hash'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContentVisit',
        ),
    ]
