# Generated by Django 5.1.7 on 2025-04-24 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='object_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='object_slug',
            field=models.CharField(default='', max_length=255, verbose_name='اسلاگ شی'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.comment', verbose_name='پاسخ والد'),
        ),
    ]
