# Generated by Django 5.1.7 on 2025-04-25 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_remove_comment_object_id_comment_object_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent_reply',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.comment', verbose_name='والد'),
        ),
    ]
