# Generated by Django 5.1.7 on 2025-04-25 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_remove_comment_parent_reply_comment_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
    ]
