# Generated by Django 5.1.7 on 2025-04-25 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_comment_level_comment_lft_comment_rght_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
    ]
