# Generated by Django 5.1.7 on 2025-05-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_historicalcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='وضعیت حذف'),
        ),
        migrations.AddField(
            model_name='historicalcomment',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='وضعیت حذف'),
        ),
    ]
