# Generated by Django 5.1.7 on 2025-04-09 10:14

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='نام کاربری')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت نام')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('skills', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='مهارت ها')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل کارمند',
                'verbose_name_plural': 'پروفایل کارمندان',
                'permissions': (('can_teacher', 'Can teacher'), ('can_employee', 'Can employee')),
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media_type', models.CharField(choices=[('telegram', 'تلگرام'), ('instagram', 'اینستاگرام'), ('linkedin', 'لینکدین'), ('x', 'ایکس'), ('threads', 'تردز'), ('facebook', 'فیسبوک'), ('youtube', 'یوتیوب'), ('github', 'گیت\u200cهاب'), ('gitlab', 'گیت\u200cلب')], max_length=20, verbose_name='نوع شبکه اجتماعی')),
                ('url', models.URLField(unique=True, verbose_name='آدرس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت نام')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('employee_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='accounts.userprofile', verbose_name='پروفایل کارمند')),
            ],
            options={
                'verbose_name': 'لینک اجتماعی',
                'verbose_name_plural': 'لینک های اجتماعی',
                'ordering': ['employee_profile', 'id'],
                'permissions': (('can_teacher', 'Can teacher'), ('can_employee', 'Can employee')),
            },
        ),
    ]
