# Generated by Django 5.1.7 on 2025-04-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userprofile',
            name='user_profil_age_be91aa_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='non_empty_bio_idx',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='bio',
            field=models.TextField(default='بیوگرافی من', verbose_name='بیوگرافی'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='employeeprofile',
            index=models.Index(fields=['username'], name='accounts_em_usernam_09d81f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='custom_user_phone_e281b2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email_verify_token'], name='custom_user_email_v_8d5cf4_idx'),
        ),
    ]
