# Generated by Django 5.1.7 on 2025-04-11 11:41

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_user'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='positions',
        ),
        migrations.AddField(
            model_name='position',
            name='roles',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='نقش های کارمند'),
        ),
    ]
