# Generated by Django 5.1.7 on 2025-04-15 13:16

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userprofile_user_profil_age_be91aa_idx_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='skills',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='roles',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='نقش های کارمند'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='مهارت ها'),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
