# Generated by Django 5.1.7 on 2025-04-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_position_positions_position_roles'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['age', 'bio', 'gender', 'job'], name='user_profil_age_8bb1cd_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='user_profile_user_idx'),
        ),
    ]
