# Generated by Django 5.1.7 on 2025-04-18 09:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_employeeprofile_skills_employeeprofile_roles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام مهارت')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فعال بودن/نبودن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
            ],
            options={
                'verbose_name': 'مهارت',
                'verbose_name_plural': 'مهارت ها',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['name'], 'verbose_name': 'شغل', 'verbose_name_plural': 'شغل ها'},
        ),
        migrations.RenameField(
            model_name='job',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='skills',
        ),
        migrations.AddField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='وضعیت فعال بودن/نبودن'),
        ),
        migrations.AddField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش'),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(default='', verbose_name='بیوگرافی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ثبت نام'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش'),
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='accounts.jobcategory', verbose_name='دسته بندی'),
        ),
    ]
