# Generated by Django 5.1.7 on 2025-04-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_skill_alter_job_options_rename_title_job_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, help_text='مهارت\u200cهای تخصصی کاربر', related_name='user_profile', to='accounts.skill', verbose_name='مهارت ها'),
        ),
    ]
