# Generated by Django 5.1.7 on 2025-04-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_user_profil_age_8bb1cd_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userprofile',
            name='user_profil_age_8bb1cd_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='user_profile_user_idx',
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['age', 'gender', 'job'], name='user_profil_age_be91aa_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(condition=models.Q(('bio__isnull', False), models.Q(('bio', ''), _negated=True)), fields=['bio'], name='non_empty_bio_idx'),
        ),
    ]
