# Generated by Django 5.1.7 on 2025-04-13 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_userprofile_user_profil_age_8bb1cd_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='accounts.job', verbose_name='شغل'),
        ),
    ]
