# Generated by Django 5.1.7 on 2025-04-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='social_media_type',
            field=models.CharField(choices=[('telegram', 'تلگرام'), ('instagram', 'اینستاگرام'), ('linkedin', 'لینکدین'), ('x', 'ایکس'), ('github', 'گیت\u200cهاب'), ('gitlab', 'گیت\u200cلب')], max_length=20, verbose_name='نوع شبکه اجتماعی'),
        ),
    ]
