# Generated by Django 5.1.7 on 2025-04-14 19:27

import blog.models
import django.db.models.deletion
import mptt.fields
import taggit.managers
import utils.custom_fields.slug_field
import utils.validate.validators_image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', utils.custom_fields.slug_field.AutoSlugField(editable=False, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childrens', to='blog.articlecategory')),
            ],
            options={
                'verbose_name': 'Article Category',
                'verbose_name_plural': 'Article Categories',
                'db_table': 'article_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', utils.custom_fields.slug_field.AutoSlugField(editable=False, max_length=255, unique=True)),
                ('image', models.ImageField(upload_to=blog.models.get_upload_image, validators=[utils.validate.validators_image.validate_image_size])),
                ('content', models.TextField()),
                ('short_description', models.TextField()),
                ('status', models.CharField(choices=[('-در-حال-بررسی', 'در-حال-بررسی'), ('منتشر-شده-است', 'منتشر-شده-است'), ('نیاز-به-اصلاح دارد', 'نیاز-به-اصلاح دارد'), ('تایید-نشد', 'تایید-نشد')], default='-در-حال-بررسی', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('category', models.ManyToManyField(db_table='article_category_link', related_name='articles', to='blog.articlecategory')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'db_table': 'article',
                'ordering': ['-created_at'],
            },
        ),
    ]
