# Generated by Django 5.1.7 on 2025-04-06 08:53

import blog.models
import django.db.models.deletion
import markdownfield.models
import taggit.managers
import utils.slug_field
import utils.validators_image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecategory',
            name='slug',
            field=utils.slug_field.AutoSlugField(editable=False, max_length=255, unique=True),
        ),
        migrations.AlterModelTable(
            name='articlecategory',
            table='article_category',
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', utils.slug_field.AutoSlugField(editable=False, max_length=255, unique=True)),
                ('image', models.ImageField(upload_to=blog.models.get_upload_image, validators=[utils.validators_image.validate_image_size])),
                ('content', markdownfield.models.MarkdownField(rendered_field='content_rendered')),
                ('content_rendered', markdownfield.models.RenderedMarkdownField()),
                ('short_description', models.TextField()),
                ('status', models.CharField(choices=[('-در-حال-بررسی', 'در-حال-بررسی'), ('منتشر-شده-است', 'منتشر-شده-است'), ('نیاز-به-اصلاح دارد', 'نیاز-به-اصلاح دارد'), ('تایید-نشد', 'تایید-نشد')], default='-در-حال-بررسی', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
                ('category', models.ManyToManyField(db_table='article_category_link', related_name='articles', to='blog.articlecategory')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'db_table': 'article',
                'ordering': ['-created_at'],
            },
        ),
    ]
