# Generated by Django 5.1.7 on 2025-04-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_articlecategory_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content_rendered',
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(),
        ),
    ]
