# Generated by Django 5.1.7 on 2025-04-07 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='season',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='season',
            name='slug',
        ),
    ]
