# Generated by Django 5.1.7 on 2025-04-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('تمام شده', 'تمام شده'), ('در حال پیشرفت', 'در حال پیشرفت'), ('در حال انتظار', 'در حال انتظار'), ('کنسل شده', 'کنسل شده'), ('بایگانی شده', 'بایگانی شده')], default='در حال انتظار', max_length=30, verbose_name='وضعیت دوره'),
        ),
    ]
