# Generated by Django 5.1.7 on 2025-04-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('PERSIAN', 'فارسی'), ('ENGLISH', 'انگلیسی'), ('AZERBAIJANI_TURKIC', 'ترکی آذربایجانی')], default='fa', max_length=50, verbose_name='زبان دوره'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='last_lesson_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ آخرین بروزرسانی جلسات'),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='پیش نیاز'),
        ),
    ]
