# Generated by Django 5.1.7 on 2025-04-15 12:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_faq'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['slug'], name='courses_cou_slug_2e551f_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_deleted', 'is_published'], name='courses_cou_is_dele_18a4ad_idx'),
        ),
        migrations.AddIndex(
            model_name='coursecategory',
            index=models.Index(fields=['slug'], name='courses_cou_slug_6be797_idx'),
        ),
    ]
