# Generated by Django 5.1.7 on 2025-04-03 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['created_at'], 'verbose_name': 'دوره', 'verbose_name_plural': 'دوره ها'},
        ),
    ]
