# Generated by Django 5.1.7 on 2025-04-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_season_unique_together_remove_season_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='وضعیت حذف'),
        ),
    ]
