# Generated by Django 5.1.7 on 2025-04-03 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecategory',
            name='count_courses',
        ),
    ]
