# Generated by Django 5.1.7 on 2025-04-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_courserequest_target_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserequest',
            name='target_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
