# Generated by Django 5.1.7 on 2025-04-08 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_season_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='learninglevel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='learningpath',
            name='description',
        ),
    ]
