# Generated by Django 5.1.7 on 2025-04-13 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_language_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='courses.course', verbose_name='دوره'),
        ),
    ]
