# Generated by Django 5.1.7 on 2025-04-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_courses_cou_slug_2e551f_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order', 'created_at', 'id'], 'verbose_name': 'درس', 'verbose_name_plural': 'درس ها'},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['order', 'created_at', 'id'], 'verbose_name': 'فصل', 'verbose_name_plural': 'فصل ها'},
        ),
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ترتیب دوره'),
        ),
        migrations.AddField(
            model_name='season',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ترتیب دوره'),
        ),
    ]
