# Generated by Django 5.1.7 on 2025-04-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_lesson_options_alter_season_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['order', 'created_at', 'id'], 'verbose_name': 'سوال متداول', 'verbose_name_plural': 'سوالات متداول'},
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['order', 'created_at', 'id'], 'verbose_name': 'ویژگی', 'verbose_name_plural': 'ویژگی ها'},
        ),
        migrations.AddField(
            model_name='faq',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ترتیب دوره'),
        ),
        migrations.AddField(
            model_name='feature',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ترتیب دوره'),
        ),
    ]
