# Generated by Django 5.1.7 on 2025-04-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_coursecategory_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='وضعیت حذف'),
        ),
    ]
