# Generated by Django 5.1.7 on 2025-04-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_coursecategory_count_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='discount_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضای تخفیف'),
        ),
    ]
