# Generated by Django 5.1.7 on 2025-04-21 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_courserequest_target_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courserequest',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_course_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='courserequest',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='learningpath',
            name='start_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths_start', to='courses.learninglevel', verbose_name='شروع سطح آموزشی'),
        ),
    ]
