# Generated by Django 5.1.7 on 2025-04-15 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_faq_options_alter_feature_options_faq_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='season_duration',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='مدت زمان فصل'),
        ),
    ]
