# Generated by Django 5.1.7 on 2025-04-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_price_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='price',
            name='final_price',
            field=models.PositiveIntegerField(editable=False, verbose_name='قیمت نهایی'),
        ),
    ]
