# Generated by Django 5.1.7 on 2025-04-04 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_price_discount_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningpath',
            name='end_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths_end', to='courses.learninglevel', verbose_name='پایان سطح آموزشی'),
        ),
    ]
