# Generated by Django 5.1.7 on 2025-04-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lesson_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='url_files',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='آدرس فایل ها'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='url_video',
            field=models.URLField(unique=True, verbose_name='آدرس ویدیو'),
        ),
    ]
