# Generated by Django 5.1.7 on 2025-04-15 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_lesson_season_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='season_duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='season',
            old_name='season_duration',
            new_name='duration',
        ),
    ]
