# Generated by Django 5.1.7 on 2025-04-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_lesson_url_files_alter_lesson_url_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='has_seasons',
            field=models.BooleanField(default=False, editable=False, verbose_name='فصل بندی شده/نشده'),
        ),
    ]
