# Generated by Django 5.1.7 on 2025-04-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_learningpath_end_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('اتمام-یافته', 'اتمام-یافته'), ('در-حال-تکمیل', 'در-حال-تکمیل'), ('به-زودی-شروع-میشود', 'در-حال-انتظار'), ('کنسل-شده', 'کنسل-شده')], default='به-زودی-شروع-میشود', max_length=30, verbose_name='وضعیت دوره'),
        ),
    ]
