# Generated by Django 5.1.7 on 2025-04-13 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_price_updated_at_alter_price_final_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='end_date',
        ),
    ]
