# Generated by Django 5.1.7 on 2025-04-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_historicalcourserequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserequest',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcourserequest',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
