# Generated by Django 5.1.7 on 2025-04-15 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_rename_season_duration_lesson_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_duration',
            new_name='duration',
        ),
    ]
