# Generated by Django 5.1.7 on 2025-04-08 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_has_seasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='courses.season', verbose_name='فصل'),
        ),
    ]
