# Generated by Django 5.1.7 on 2025-04-16 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_rename_course_duration_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='published_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='تاریخ انتشار'),
        ),
    ]
