# Generated by Django 5.1.7 on 2025-04-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_lesson_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='has_seasons',
            field=models.BooleanField(default=False, verbose_name='فصل بندی شده/نشده'),
        ),
    ]
