# Generated by Django 5.1.7 on 2025-04-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_courserequest_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('az', 'ترکی آذربایجانی')], max_length=50, verbose_name='زبان دوره'),
        ),
    ]
