# Generated by Django 5.1.7 on 2025-04-22 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_course_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonmedia',
            options={'verbose_name': 'رسانه\u200cی درس', 'verbose_name_plural': 'رسانه\u200cهای درس'},
        ),
        migrations.AlterField(
            model_name='lessonmedia',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='media', to='courses.course'),
            preserve_default=False,
        ),
    ]
