# Generated by Django 5.1.7 on 2025-04-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_published_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['published_at', 'id'], 'verbose_name': 'دوره', 'verbose_name_plural': 'دوره ها'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order', 'published_at', 'id'], 'verbose_name': 'درس', 'verbose_name_plural': 'درس ها'},
        ),
        migrations.RemoveField(
            model_name='season',
            name='description',
        ),
        migrations.RemoveField(
            model_name='season',
            name='is_published',
        ),
        migrations.AddField(
            model_name='lesson',
            name='published_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='تاریخ انتشار'),
        ),
    ]
