# Generated by Django 5.1.7 on 2025-04-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_course_has_seasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='url_video',
            field=models.URLField(blank=True, help_text='این فیلد برای ویدیوهای کوتاه و آشنایی با دوره یا معرفی استاد است.', null=True, unique=True, verbose_name='لینک ویدیو'),
        ),
    ]
