# Generated by Django 5.1.7 on 2025-04-22 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_lessonmedia_options_alter_lessonmedia_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courserequest',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'درخواست', 'verbose_name_plural': 'درخواست ها'},
        ),
        migrations.AlterModelOptions(
            name='historicalcourserequest',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical درخواست', 'verbose_name_plural': 'historical درخواست ها'},
        ),
    ]
