# Generated by Django 5.1.7 on 2025-04-17 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_lesson_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='count_comments',
        ),
    ]
