# Generated by Django 5.1.7 on 2025-04-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_courserequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserequest',
            name='status',
            field=models.CharField(choices=[('pending', 'در حال بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('need_revision', 'نیاز به اصلاح'), ('draft', 'پیش نویس')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalcourserequest',
            name='status',
            field=models.CharField(choices=[('pending', 'در حال بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('need_revision', 'نیاز به اصلاح'), ('draft', 'پیش نویس')], default='pending', max_length=20),
        ),
    ]
