# Generated by Django 5.1.7 on 2025-04-08 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_lesson_created_at_lesson_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['created_at', 'id'], 'verbose_name': 'فصل', 'verbose_name_plural': 'فصل ها'},
        ),
    ]
