# Generated by Django 5.1.7 on 2025-04-08 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_season_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['created_at', 'id'], 'verbose_name': 'درس', 'verbose_name_plural': 'درس ها'},
        ),
    ]
