# Generated by Django 5.1.7 on 2025-04-17 11:14

import courses.models
import utils.validate.validators_image
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_remove_course_count_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=courses.models.get_upload_path, validators=[utils.validate.validators_image.validate_image_size], verbose_name='بنر دوره'),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'تکمیل شده'), ('IN_PROGRESS', 'در حال برگذاری'), ('UPCOMING', 'به زودی'), ('CANCELLED', 'لغو شده')], max_length=30, verbose_name='وضعیت دوره'),
        ),
    ]
