# Generated by Django 5.1.7 on 2025-04-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_courserequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserequest',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcourserequest',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
