# Generated by Django 5.1.7 on 2025-04-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_course_banner_alter_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='وضعیت حذف'),
        ),
        migrations.AddField(
            model_name='feature',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='وضعیت حذف'),
        ),
    ]
