# Generated by Django 5.1.7 on 2025-04-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_courserequest_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserequest',
            name='need_revision',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcourserequest',
            name='need_revision',
            field=models.BooleanField(default=False),
        ),
    ]
