# Generated by Django 5.1.7 on 2025-04-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_courserequest_need_revision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserequest',
            name='action',
            field=models.CharField(choices=[('add', 'ایجاد'), ('update', 'ویرایش'), ('delete', 'حذف')], max_length=20),
        ),
        migrations.AlterField(
            model_name='courserequest',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'در حال بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('need_revision', 'نیاز به اصلاح'), ('draft', 'پیش نویس')], default='draft', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcourserequest',
            name='action',
            field=models.CharField(choices=[('add', 'ایجاد'), ('update', 'ویرایش'), ('delete', 'حذف')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalcourserequest',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'در حال بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('need_revision', 'نیاز به اصلاح'), ('draft', 'پیش نویس')], default='draft', max_length=20, null=True),
        ),
    ]
