# Generated by Django 5.1.7 on 2025-04-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_alter_course_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='count_comments',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='تعداد نظر ها'),
        ),
        migrations.AddField(
            model_name='course',
            name='unique_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faq',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='وضعیت حذف'),
        ),
    ]
