# Generated by Django 5.1.7 on 2025-04-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_alter_course_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='count_comment',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='تعداد نظر ها'),
        ),
    ]
