# Generated by Django 5.1.7 on 2025-04-29 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_course_count_comments_course_unique_views_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='unique_views',
            new_name='count_unique_views',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='views',
            new_name='count_views',
        ),
    ]
