# Generated by Django 5.1.7 on 2025-04-25 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_course_count_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='count_comment',
            new_name='count_comments',
        ),
    ]
