# Generated by Django 5.1.7 on 2025-04-25 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_rename_count_comment_course_count_comments'),
    ]

    operations = [
    ]
