# Generated by Django 5.1.7 on 2025-04-25 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_auto_20250425_1750'),
    ]

    operations = [
    ]
